#!/usr/bin/env python3
"""03_storage.py — provision state/artifact storage for llmops-agentic-system (idempotent).

Creates (all tagged project=llmops-agentic-system):
  - S3 data bucket (default llmops-agentic-<account_id>-<region>):
      versioning ON, SSE-S3 (AES256), public access block ALL,
      lifecycle: objects under runs/ expire after 90 days,
      CORS: PUT/GET/HEAD from the console's HTTP API origin only (browser-direct
        dataset upload via presigned PUT; skipped, never wildcarded, if unresolved)
      code/eval/: the canonical pairwise judge prompt (pipeline/eval/), read-back verified.
        The eval prompt is told to read it and to ESCALATE rather than compose its own, so
        this upload is what makes a scoring stage possible at all -- and the digest it
        returns is what report.json records as judge_prompt_sha256.
      skills/: the SKILL.md trees the harness configs mount, mirrored with --skills-src
        so harnesses can move off `git` sources; each SKILL.md is validated for YAML
        frontmatter BEFORE upload (a bad source fails at SESSION START, not at
        UpdateHarness, so this must land before any source is switched)
  - DynamoDB llmops-pipeline-runs  (PK run_id S; GSI job_name-index on job_name S;
      on-demand; point-in-time recovery ON)
  - DynamoDB llmops-stage-events   (PK run_id S, SK sk S; on-demand)
  - DynamoDB llmops-cost-estimates (PK id S; GSI project-created_at-index; PITR on)
  - DynamoDB llmops-cost-actuals   (PK project S, SK sk S; PITR on)
  - EventBridge custom bus llmops-pipeline
  - SNS topic llmops-escalations
  - Macie coverage over customer-data/: always REPORTED, created only with
      --enable-pii-scan (a scheduled job is recurring paid work; and an ENABLED Macie
      session is not coverage — live, the account's only job was a ONE_TIME job from
      2021 over 25 unrelated buckets that processed 0 objects)
  - SSM parameters /llmops/storage/{bucket,runs_table,events_table,event_bus,escalations_topic_arn}

--dry-run prints the would-create plan without any AWS write. STS is only needed to
derive the default bucket name / topic check; pass --account-id for a fully offline dry-run.

Usage:
  python deploy/03_storage.py --region us-east-1 [--bucket NAME] [--dry-run]
  python deploy/03_storage.py --region us-east-1 --account-id 123456789012 --dry-run  # offline
"""
import argparse
import hashlib
import json
import pathlib
import sys

import boto3
from botocore.exceptions import ClientError

TAG_KEY, TAG_VAL = "project", "llmops-agentic-system"
RUNS_TABLE = "llmops-pipeline-runs"
EVENTS_TABLE = "llmops-stage-events"
#: Cost estimates and their approval decisions. Separate from the console's generic
#: table because an approval is an audit record: who asked, who approved, on what
#: number, at what time. PITR is on for the same reason.
ESTIMATES_TABLE = "llmops-cost-estimates"
#: Reconciled actuals, one row per (period, run, category), plus reserved #audit#/
#: #finding# rows from the finops agent. (PK, SK) mirrors llmops-stage-events so a
#: range query by period is natural.
ACTUALS_TABLE = "llmops-cost-actuals"
#: Tasks-tab consultations (goal → plan → signed acceptance → dispatch). PITR on:
#: the approval records inside are the "a human decided this" audit artifacts.
TASKS_TABLE = "llmops-tasks"
EVENT_BUS = "llmops-pipeline"
SNS_TOPIC = "llmops-escalations"
#: Asymmetric signing key for plan-acceptance records. The private half never leaves
#: KMS hardware, which is what makes an approval unforgeable after the fact.
APPROVAL_KEY_ALIAS = "alias/llmops-approval"
RUNS_EXPIRE_DAYS = 90
#: The admin console Lambda, whose HTTP API origin is the only origin allowed to upload.
#: Must match FN in deploy/console/deploy.sh.
CONSOLE_FN = "llmops-admin"
#: Where the console's presigned PUT lands a customer's dataset, and therefore the only
#: prefix a PII classification job should pay to read. Must match CUSTOMER_DATA_PREFIX in
#: deploy/console/lambda_function.py and the prefix both agent prompts name.
CUSTOMER_DATA_PREFIX = "customer-data"


def safe_client(service, region, dry):
    """boto3 client, but degrade to None under --dry-run when the environment has
    no usable AWS config at all (fully offline dry-run with --account-id)."""
    try:
        return boto3.client(service, region_name=region)
    except Exception:
        if dry:
            return None
        raise


def console_origin(region, dry, override=None):
    """The one browser origin allowed to PUT a customer dataset into this bucket.

    Resolved from the console's own HTTP API rather than configured twice: the API id is
    generated by apigatewayv2 at create time (deploy/console/deploy.sh), so hardcoding it
    here would rot the first time the stack is rebuilt in a new account.

    Returns "" when it cannot be resolved, and the caller then SKIPS CORS rather than
    falling back to "*". A wildcard AllowedOrigins would let any page on the internet
    complete a presigned PUT it got hold of, which is exactly the boundary the 15-minute
    URL lifetime exists to keep narrow -- a silent security downgrade traded for a
    convenience nobody asked for.
    """
    if override:
        return override.rstrip("/")
    try:
        api = boto3.client("apigatewayv2", region_name=region)
        for item in api.get_apis().get("Items", []):
            if item.get("Name") == f"{CONSOLE_FN}-api":
                return f"https://{item['ApiId']}.execute-api.{region}.amazonaws.com"
    except Exception:
        pass
    return ""


def ensure_cors(s3, bucket, origin, dry):
    """Allow the console page to PUT a dataset straight to S3.

    A presigned PUT from the dashboard is a cross-origin request, so without a CORS rule
    the browser fails at the PREFLIGHT -- before the signature is ever checked. Verified
    live: this bucket returned NoSuchCORSConfiguration, and there was no step here to
    extend, so browser upload was impossible no matter how correct the URL was. The
    failure surfaces in the console as an opaque network error, which reads as an S3
    permission problem and costs hours in the wrong place.

    Scoped deliberately:
      - PUT only (plus the HEAD/GET a resumable client uses to check what landed). No
        DELETE: nothing in the product asks a browser to remove a customer's dataset, and
        a presigned URL is a bearer token.
      - ExposeHeaders ETag so the client can report what S3 actually stored.
      - One origin. See console_origin() for why never "*".
    """
    if not origin:
        return "skipped (console origin unresolved; pass --console-origin)"
    rules = [{
        "ID": "console-presigned-upload",
        "AllowedMethods": ["PUT", "GET", "HEAD"],
        "AllowedOrigins": [origin],
        # content-type and the x-amz-* signed headers (server-side-encryption) ride on
        # the PUT, so the preflight must be allowed to ask for them.
        "AllowedHeaders": ["content-type", "x-amz-server-side-encryption",
                           "x-amz-content-sha256", "x-amz-date"],
        "ExposeHeaders": ["ETag"],
        "MaxAgeSeconds": 3000,
    }]
    if dry:
        return f"would allow PUT from {origin}"
    s3.put_bucket_cors(Bucket=bucket, CORSConfiguration={"CORSRules": rules})
    return f"PUT allowed from {origin}"


def ensure_bucket(s3, bucket, region, dry):
    exists = True
    try:
        s3.head_bucket(Bucket=bucket)
    except Exception:
        exists = False
    if dry:
        return "exists" if exists else "would create"
    if not exists:
        kwargs = {"Bucket": bucket}
        if region != "us-east-1":  # us-east-1 rejects a LocationConstraint
            kwargs["CreateBucketConfiguration"] = {"LocationConstraint": region}
        s3.create_bucket(**kwargs)
        s3.get_waiter("bucket_exists").wait(Bucket=bucket)
    # The settings below are idempotent puts — safe to reapply on every run.
    s3.put_bucket_versioning(Bucket=bucket,
                             VersioningConfiguration={"Status": "Enabled"})
    s3.put_bucket_encryption(Bucket=bucket, ServerSideEncryptionConfiguration={
        "Rules": [{"ApplyServerSideEncryptionByDefault": {"SSEAlgorithm": "AES256"}}]})
    s3.put_public_access_block(Bucket=bucket, PublicAccessBlockConfiguration={
        "BlockPublicAcls": True, "IgnorePublicAcls": True,
        "BlockPublicPolicy": True, "RestrictPublicBuckets": True})
    s3.put_bucket_lifecycle_configuration(Bucket=bucket, LifecycleConfiguration={
        "Rules": [{
            "ID": f"expire-runs-{RUNS_EXPIRE_DAYS}d",
            "Status": "Enabled",
            "Filter": {"Prefix": "runs/"},
            "Expiration": {"Days": RUNS_EXPIRE_DAYS},
            "NoncurrentVersionExpiration": {"NoncurrentDays": RUNS_EXPIRE_DAYS},
        }]})
    s3.put_bucket_tagging(Bucket=bucket,
                          Tagging={"TagSet": [{"Key": TAG_KEY, "Value": TAG_VAL}]})
    return "exists" if exists else "created"


def ensure_contracts(s3, bucket, dry):
    """Upload pipeline/contracts/ to s3://<bucket>/contracts/.

    The finops harness is told to "read pipeline/contracts/cost_model.py and call it
    rather than recomputing costs in prose" -- a repo-relative path that means nothing
    inside an AgentCore container, which has no checkout. Proven live on the first
    pricing_refresh: the agent looked for the module on its filesystem, as an installed
    package, and in S3, found none of the three, and fell back to applying the merge
    precedence by hand -- stamping its own 37-SKU card `v1-DRAFT-noncanonical` because
    the `fallback_static` tier lives inside the module it could not reach.

    Uploading here rather than in a bespoke script keeps the module beside the buckets
    and tables the rest of the pipeline reads: one place that answers "what state does
    a fresh container start from". Lambdas keep vendoring the contracts into their zip
    (07_lambdas.py) -- a Lambda has no network guarantee to S3 at import time, whereas
    the harness does.
    """
    src = pathlib.Path(__file__).resolve().parent.parent / "pipeline" / "contracts"
    files = sorted(p for p in src.glob("*") if p.is_file())
    if dry:
        return {"would": f"upload {len(files)} contract files", "to": f"s3://{bucket}/contracts/"}
    for p in files:
        s3.upload_file(str(p), bucket, f"contracts/{p.name}")
        # Mirror under the repo-relative key too. The harness prompts cite the module
        # as pipeline/contracts/cost_model.py (its path in the repo), and a live
        # pricing_refresh showed the agent probing exactly that string as an S3 key
        # before giving up. Two keys, one upload path — cheaper than arguing with
        # every future prompt about which spelling is canonical.
        s3.upload_file(str(p), bucket, f"pipeline/contracts/{p.name}")
    return {"uploaded": [p.name for p in files],
            "to": [f"s3://{bucket}/contracts/", f"s3://{bucket}/pipeline/contracts/"]}


def ensure_code(s3, bucket, dry):
    """Upload pipeline/training/distill/ to s3://<bucket>/code/distill/ and VERIFY it.

    The finetune agent authored its own train_qlora.py on every run because the
    canonical script was IAM-unreadable -- its own docstring said so verbatim on
    run-20260811T165529Z-ce628817 ("canonical code/train_qlora.py unreadable by
    harness role"). Codegen roulette: the same agent produced a working trainer on
    r5 and r6c and an UnboundLocalError on r6a. The cure is the skills argument over
    again: a canonical artifact the role can READ and may not WRITE, mirrored by the
    deploy so drift is a deploy-time diff, not a per-run surprise. Read-back verified
    byte-for-byte under the deployer's credentials (the ROLE's read is granted in
    deploy/iam/harness_execution_role.json, S3CanonicalCodeReadOnly).
    """
    src_dir = pathlib.Path(__file__).resolve().parent.parent / "pipeline" / "training" / "distill"
    files = sorted(p for p in src_dir.glob("*") if p.is_file())
    if not files:
        raise SystemExit("pipeline/training/distill/ is empty -- the finetune prompt "
                         "names this mirror, so an empty upload would strand every launch")
    if dry:
        return {"would": f"upload {len(files)} canonical code files",
                "to": f"s3://{bucket}/code/distill/"}
    verified = []
    for p in files:
        key = f"code/distill/{p.name}"
        s3.upload_file(str(p), bucket, key)
        body = s3.get_object(Bucket=bucket, Key=key)["Body"].read()
        if body != p.read_bytes():
            raise SystemExit(f"read-back mismatch for s3://{bucket}/{key}")
        verified.append(p.name)
    return {"uploaded_and_verified": verified, "to": f"s3://{bucket}/code/distill/"}


#: The one prefix the eval instrument is mirrored to. Under code/ because the harness role
#: already has GetObject on code/* and no PutObject anywhere in it -- readable by the agent
#: that consumes it, not writable by the agent it measures.
EVAL_PREFIX = "code/eval/"

#: Same property, third artifact: the canonical vision trainer. (The vision mAP SCORER
#: needs no prefix of its own -- it lives in pipeline/eval/, so ensure_eval_instrument
#: already mirrors and digests it with the judge prompt.)
VISION_PREFIX = "code/vision/"


def ensure_vision_code(s3, bucket, dry):
    """Upload pipeline/training/vision/ to s3://<bucket>/code/vision/ and VERIFY it.

    Same argument as ensure_code one screen up, applied to the detection trainer: the
    finetune prompt names this mirror as CANONICAL for pipeline_mode="vision", so an
    empty or drifted upload is a per-run codegen surprise instead of a deploy-time diff.
    Under code/ so the harness role's existing S3CanonicalCodeReadOnly grant covers it --
    readable by the agent, writable only by the deployer. Zero IAM change by design.
    """
    src_dir = pathlib.Path(__file__).resolve().parent.parent / "pipeline" / "training" / "vision"
    files = sorted(p for p in src_dir.glob("*") if p.is_file())
    if not files:
        raise SystemExit("pipeline/training/vision/ is empty -- the finetune prompt names "
                         "this mirror for vision runs, so an empty upload would strand "
                         "every vision launch")
    if dry:
        return {"would": f"upload {len(files)} canonical vision trainer files",
                "to": f"s3://{bucket}/{VISION_PREFIX}"}
    verified = {}
    for p in files:
        key = f"{VISION_PREFIX}{p.name}"
        body = p.read_bytes()
        s3.upload_file(str(p), bucket, key)
        got = s3.get_object(Bucket=bucket, Key=key)["Body"].read()
        if got != body:
            raise SystemExit(f"read-back mismatch for s3://{bucket}/{key}")
        verified[p.name] = hashlib.sha256(body).hexdigest()
    return {"uploaded_and_verified": verified, "to": f"s3://{bucket}/{VISION_PREFIX}"}


def ensure_eval_instrument(s3, bucket, dry):
    """Upload pipeline/eval/ to s3://<bucket>/code/eval/ and VERIFY it byte-for-byte.

    Same argument as ensure_code one function up, applied to the measuring instrument instead
    of the trainer. The eval prompt said "fixed judge prompts" and fixed none, so the pairwise
    judge prompt was re-authored every run and two runs' judge_score numbers were not strictly
    comparable. r5 reported `judge_ties: 0` -- read at the time as "no ties in 40 items", it
    was an artifact of an A-or-B-only prompt that run wrote; the canonical text ties on 38% of
    in-distribution items on the same task.

    Under `code/` on purpose, not a new prefix: the harness role's S3CanonicalCodeReadOnly
    already grants GetObject on `code/*` and nothing grants it PutObject there, which is
    exactly the property a canonical artifact needs (readable, not writable by the thing that
    consumes it). A new `eval/` prefix would have needed a new grant to say the same thing.

    The digest is returned so the deploy log records WHICH instrument is live: report.json
    carries judge_prompt_sha256, and comparing two runs is then a digest comparison rather
    than an argument.
    """
    src_dir = pathlib.Path(__file__).resolve().parent.parent / "pipeline" / "eval"
    files = sorted(p for p in src_dir.glob("*") if p.is_file())
    if not files:
        raise SystemExit("pipeline/eval/ is empty -- the eval prompt names this mirror and is "
                         "told to escalate rather than author its own judge prompt, so an "
                         "empty upload would stall every scoring stage")
    # One prefix, spelled once. The dry-run branch and the upload branch each had their own
    # f-string first, and a mutation test proved they could disagree while every guard stayed
    # green: the guard derives the prompt's URI from the DRY report, so `--dry-run` could
    # promise code/eval/ while the real upload wrote somewhere else -- the "no deploy path"
    # failure with a deploy path that lies. EVAL_PREFIX is the reason that mutant now dies.
    prefix = EVAL_PREFIX
    if dry:
        return {"would": f"upload {len(files)} eval instrument files",
                "to": f"s3://{bucket}/{prefix}"}
    verified = {}
    for p in files:
        key = f"{prefix}{p.name}"
        body = p.read_bytes()
        s3.upload_file(str(p), bucket, key)
        got = s3.get_object(Bucket=bucket, Key=key)["Body"].read()
        if got != body:
            raise SystemExit(f"read-back mismatch for s3://{bucket}/{key}")
        verified[p.name] = hashlib.sha256(body).hexdigest()
    return {"uploaded_and_verified": verified, "to": f"s3://{bucket}/{prefix}"}


def mounted_skills(repo):
    """Every skill path the harness configs mount, mapped to the harnesses mounting it.

    Derived from `agents/*/harness.json` rather than from a hand-kept list here, because
    a hand-kept list is exactly the thing that goes stale silently: a new mount would be
    absent from S3, and a missing skill source does not fail at `UpdateHarness` -- it
    fails at SESSION START, on every invocation, with the config still reading healthy.
    So the sync follows the configs by construction.

    BOTH `git` and `s3` sources are collected, and that is the load-bearing detail. The
    first version collected only `git`, on the reasoning that "an entry already on s3
    needs no upload" -- which inverts the dependency the moment the migration lands. Once
    every source reads `s3://<bucket>/skills/...`, S3 is the ONLY copy the agents ever
    see, so it is exactly then that the mirror must keep syncing it. A git-only sync would
    have gone quietly empty at the switch, taking its own coverage guard with it (0 mounts
    compared against 0 git sources passes), and the next skill edit would never reach any
    agent while every config still read healthy.

    An `s3` entry's repo-relative path is recovered from its URI rather than from a
    `path` key, because the s3 source shape is a single `uri` with no path field. The
    bucket is dropped: what is returned is the path both source kinds name identically
    (`skills/llmops/llm-evaluation`), which is what makes the key mechanical.

    An entry may carry sibling keys (one currently carries a `_comment`), so membership is
    tested by key rather than by taking the entry's first key.
    """
    mounts = {}
    for cfg in sorted((repo / "agents").glob("*/harness.json")):
        for skill in json.loads(cfg.read_text()).get("skills") or []:
            path = None
            git = skill.get("git")
            s3src = skill.get("s3")
            if git and git.get("path"):
                path = git["path"]
            elif isinstance(s3src, dict) and s3src.get("uri"):
                # s3://<bucket>/<path> -> <path>. A placeholder bucket (<DATA_BUCKET>) is
                # unresolved in the repo file and is discarded here along with the real
                # one, so the mirror plan is the same before and after substitution.
                rest = s3src["uri"].split("://", 1)[-1]
                path = rest.split("/", 1)[1].rstrip("/") if "/" in rest else None
            if path:
                mounts.setdefault(path, []).append(cfg.parent.name)
    return mounts


def skill_frontmatter(path):
    """Return (name, description) from a SKILL.md, or raise ValueError saying what is wrong.

    This is the #1 skills failure and it is undocumented: a SKILL.md that does not START
    with YAML frontmatter carrying `name` and `description` is accepted by the control
    plane and then kills every session at start with

        runtimeClientError: SKILL.md in .agents/skills/... has no YAML frontmatter

    Validating here -- before the object is uploaded and long before any source is
    switched -- is the whole reason this step exists as a gate rather than a copy loop.
    Parsed by hand rather than with a YAML dependency: the requirement is only that the
    first line is `---` and that two scalar keys appear before the closing `---`, and a
    deploy script that needs PyYAML installed is a new way for a deploy to fail.
    """
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---"):
        raise ValueError(f"{path} does not start with '---'; every session would fail "
                         "at start with 'has no YAML frontmatter'")
    end = text.find("\n---", 3)
    if end == -1:
        raise ValueError(f"{path} opens frontmatter with '---' but never closes it")
    found = {}
    for line in text[3:end].splitlines():
        if ":" in line and not line.startswith((" ", "\t", "#")):
            k, _, v = line.partition(":")
            found[k.strip()] = v.strip()
    missing = [k for k in ("name", "description") if not found.get(k)]
    if missing:
        raise ValueError(f"{path} frontmatter is missing {missing}; the agent addresses a "
                         "skill by its frontmatter `name`, so an absent one is unreachable")
    return found["name"], found["description"]


def ensure_skills(s3, bucket, dry, src=None, repo=None):
    """Mirror the mounted skills to s3://<bucket>/<repo-relative path>/ and VERIFY them.

    This exists to be a prerequisite, not an optimization. Moving the harnesses off `git`
    skill sources is worth doing for two reasons -- a git source has no branch field, so
    it always reads the skills repo's DEFAULT branch and main-branch drift silently
    changes production agent behaviour; and a VPC-mode harness cannot reach GitHub at all
    -- but the order cannot be reversed. Switch the sources first and `UpdateHarness`
    accepts it, mints a version, reports READY, and then every session fails at start.
    So: objects land and are validated here, and only then may a source move.

    The S3 key mirrors the repo-relative path (`skills/llmops/llm-evaluation`), so the
    URI a harness config needs is mechanical -- `s3://<bucket>/<the same path the git
    source already names>` -- rather than a second naming scheme to keep in sync.

    A skill the configs mount but the source tree does not have is a hard error, not a
    skip: quietly uploading 10 of 11 is how a source switch loses a skill.
    """
    repo = repo or pathlib.Path(__file__).resolve().parent.parent
    mounts = mounted_skills(repo)
    if not src:
        # Reported, never guessed. Uploading nothing is safe; uploading a stale or
        # partial tree and calling it verified is not.
        return {"status": "skipped (no --skills-src; pass a checkout of the skills repo)",
                "mounted": len(mounts)}
    src = pathlib.Path(src).expanduser().resolve()
    if not src.is_dir():
        raise SystemExit(f"--skills-src {src} is not a directory")

    absent = [p for p in sorted(mounts) if not (src / p / "SKILL.md").is_file()]
    if absent:
        raise SystemExit(
            f"{len(absent)} mounted skill(s) have no SKILL.md under {src}: {absent}. "
            "Switching those sources to s3 would drop them, and the failure would only "
            "appear at session start. Point --skills-src at a full checkout.")

    validated, plan = {}, []
    for path in sorted(mounts):
        name, _desc = skill_frontmatter(src / path / "SKILL.md")   # raises on a bad one
        files = sorted(p for p in (src / path).rglob("*") if p.is_file())
        validated[path] = {"name": name, "files": len(files),
                           "uri": f"s3://{bucket}/{path}",
                           "mounted_by": mounts[path]}
        plan.extend((p, f"{path}/{p.relative_to(src / path).as_posix()}") for p in files)

    if dry:
        return {"status": f"would upload {len(plan)} files for {len(validated)} skills",
                "frontmatter": "validated for all mounted skills", "skills": validated}
    for local, key in plan:
        s3.upload_file(str(local), bucket, key)
    # Read back the entry point of each skill. The upload call returning without an
    # exception is not the same claim as the object being fetchable at the key a harness
    # will ask for, and the gap between those two claims is a session-start failure.
    for path in validated:
        s3.head_object(Bucket=bucket, Key=f"{path}/SKILL.md")
    return {"status": f"uploaded {len(plan)} files for {len(validated)} skills, "
                      "each SKILL.md validated and read back",
            "skills": validated}


def ensure_table(ddb, name, spec, dry, pitr=False):
    try:
        ddb.describe_table(TableName=name)
        return "exists"
    except ClientError as e:
        if e.response["Error"]["Code"] != "ResourceNotFoundException":
            raise
    except Exception:
        pass  # no credentials in offline dry-run
    if dry:
        return "would create"
    ddb.create_table(TableName=name, BillingMode="PAY_PER_REQUEST",
                     Tags=[{"Key": TAG_KEY, "Value": TAG_VAL}], **spec)
    ddb.get_waiter("table_exists").wait(TableName=name)
    if pitr:
        ddb.update_continuous_backups(
            TableName=name,
            PointInTimeRecoverySpecification={"PointInTimeRecoveryEnabled": True})
    return "created"


def ensure_approval_key(kms_client, account_id, dry):
    """ECC_NIST_P256 SIGN_VERIFY key + alias, idempotent by alias lookup.

    Key policy: root gets admin (losing key admin loses the audit trail's
    verifiability); Sign is granted via IAM identity policies (the console role's),
    which the default root-delegation policy permits; Verify/GetPublicKey likewise —
    verification is meant to be broadly available, that is the point of signing.
    """
    try:
        arn = kms_client.describe_key(KeyId=APPROVAL_KEY_ALIAS)["KeyMetadata"]["Arn"]
        return "exists", arn
    except Exception:
        pass
    if dry:
        return "would create", ""
    key = kms_client.create_key(
        Description="llmops plan-acceptance signing key (Tasks tab approvals)",
        KeyUsage="SIGN_VERIFY", KeySpec="ECC_NIST_P256",
        Tags=[{"TagKey": TAG_KEY, "TagValue": TAG_VAL}])
    arn = key["KeyMetadata"]["Arn"]
    kms_client.create_alias(AliasName=APPROVAL_KEY_ALIAS,
                            TargetKeyId=key["KeyMetadata"]["KeyId"])
    return "created", arn


def macie_job_covers(job_def, bucket, account_id, prefix=CUSTOMER_DATA_PREFIX):
    """Does this classification job's definition actually include <bucket>/<prefix>?

    Split out and pure so the coverage question is testable, because the live answer was
    counter-intuitive: the account's Macie session is ENABLED and `list_classification_jobs`
    returns a job named `scan` with status COMPLETE, which reads as "PII scanning is on".
    That job is ONE_TIME, was created 2021-02-23, names 25 unrelated buckets, and reports
    `approximateNumberOfObjectsToProcess: 0.0`. A session status is not coverage and a job
    list is not coverage; only the bucket list plus the scoping is.

    `bucketCriteria` (the tag/attribute-matching alternative to an explicit bucket list) is
    reported as unknown rather than assumed to cover or not cover -- a criteria-based job
    could match our bucket in future without this deploy knowing, and claiming either answer
    would be inventing one.
    """
    defn = job_def or {}
    if defn.get("bucketCriteria") and not defn.get("bucketDefinitions"):
        return None  # cannot be decided from the definition alone
    named = False
    for bd in defn.get("bucketDefinitions") or []:
        if bd.get("accountId") not in (None, account_id):
            continue
        if bucket in (bd.get("buckets") or []):
            named = True
    if not named:
        return False
    # A job may name our bucket and still exclude the prefix, or include only some other
    # one. An includes-block that mentions OBJECT_KEY at all is treated as authoritative:
    # if it exists and no term admits our prefix, the prefix is not covered.
    includes = ((defn.get("scoping") or {}).get("includes") or {}).get("and") or []
    key_terms = [t.get("simpleScopeTerm") for t in includes
                 if (t.get("simpleScopeTerm") or {}).get("key") == "OBJECT_KEY"]
    if key_terms and not any(
            any(str(v).startswith(prefix) or prefix.startswith(str(v))
                for v in (t.get("values") or []))
            for t in key_terms if t):
        return False
    excludes = ((defn.get("scoping") or {}).get("excludes") or {}).get("and") or []
    for term in excludes:
        simple = term.get("simpleScopeTerm") or {}
        if simple.get("key") == "OBJECT_KEY" and any(
                str(v).startswith(prefix) for v in (simple.get("values") or [])):
            return False
    return True


def ensure_pii_scan(macie, bucket, account_id, dry, enable=False):
    """Make sure something actually scans the customer's data for PII -- or say it doesn't.

    The data-prep `audit` task runs a HEURISTIC regex PII scan and states plainly in its own
    report that it is not compliance-grade. That is the honest position for an agent with a
    shell, and it is not a substitute for classification: the console's readiness panel shows
    `PII disposition` from the plan, and the customer's reasonable reading of a green panel is
    that someone looked. So this step exists to answer one question in the deploy output --
    is `s3://<bucket>/customer-data/` covered by a Macie classification job? -- and to create
    the job when asked.

    Deliberately opt-in via --enable-pii-scan, unlike every other step here. A classification
    job costs per GB scanned and, more importantly, a SCHEDULED job re-scans on its own
    forever: a deploy script that silently starts recurring paid work in someone's account is
    the same class of surprise as a silent security downgrade, just billed instead. When not
    enabled it still REPORTS the coverage gap rather than staying quiet, which is the whole
    reason the step is not simply absent (cf. ensure_topic's NO SUBSCRIBERS note).

    Two live API constraints drive the shape and neither is discoverable from the docs:
      - `UpdateClassificationJob` takes only (jobId, jobStatus). A job's bucket list and
        scoping are IMMUTABLE, so this cannot converge an existing job onto a new scope the
        way every other ensure_* here does; a wrong job must be cancelled and replaced, and
        the code says so instead of pretending an update happened.
      - `CreateClassificationJob` needs `clientToken`, and a repeat with a fresh token
        creates a SECOND job. Idempotency has to come from looking for our own job by name
        first, or every deploy adds another scanner.
    """
    job_name = f"llmops-{CUSTOMER_DATA_PREFIX}-pii"
    if macie is None:
        return {"coverage": "unknown (no macie client; offline dry-run)"}
    try:
        session = macie.get_macie_session().get("status")
    except Exception as exc:  # noqa: BLE001 — Macie not enabled in this region is a fact
        return {"coverage": "unknown", "session": f"unavailable: {type(exc).__name__}",
                "note": "Macie is not reachable here; the audit's regex scan is the only "
                        "PII check, and the readiness report must not imply otherwise."}

    ours, foreign, undecidable = None, [], []
    try:
        for item in macie.list_classification_jobs().get("items", []):
            covers = macie_job_covers(item.get("s3JobDefinition"), bucket, account_id)
            if item.get("name") == job_name:
                ours = item
            elif covers:
                foreign.append(f"{item.get('name')} ({item.get('jobStatus')})")
            elif covers is None:
                undecidable.append(item.get("name"))
    except Exception as exc:  # noqa: BLE001
        return {"coverage": "unknown", "session": session,
                "note": f"could not list classification jobs: {exc}"}

    res = {"session": session, "job": job_name}
    if foreign:
        res["also_covered_by"] = foreign
    if undecidable:
        # Not folded into "covered": a bucketCriteria job might match our bucket by tag.
        res["undecidable_jobs"] = undecidable
    if ours:
        status = ours.get("jobStatus")
        res["coverage"] = f"job exists ({ours.get('jobType')}, {status})"
        res["job_id"] = ours.get("jobId")
        if not macie_job_covers(ours.get("s3JobDefinition"), bucket, account_id):
            # The name matches but the scope does not, and no API can fix that in place.
            res["coverage"] = (f"job {job_name} exists but does NOT cover "
                               f"{CUSTOMER_DATA_PREFIX}/ -- a job's scope is immutable "
                               "(UpdateClassificationJob takes only jobStatus); cancel it "
                               "and re-run to create a correctly scoped replacement")
        return res
    if not enable:
        res["coverage"] = (
            f"NO JOB SCANS {CUSTOMER_DATA_PREFIX}/ -- the only PII check on customer data is "
            "the data-prep audit's heuristic regex scan, which says so in its own report. "
            "Re-run with --enable-pii-scan to create a scheduled Macie job (billed per GB).")
        return res
    if dry:
        res["coverage"] = f"would create SCHEDULED daily job over {CUSTOMER_DATA_PREFIX}/"
        return res
    job = macie.create_classification_job(
        name=job_name,
        # >=33 chars, and stable per (bucket, prefix): a fresh random token on every deploy
        # would create a second job each time rather than failing as a duplicate.
        clientToken=f"llmops-pii-{bucket}-{CUSTOMER_DATA_PREFIX}"[:64],
        jobType="SCHEDULED",
        scheduleFrequency={"dailySchedule": {}},
        initialRun=True,
        description="llmops: classify customer-uploaded datasets for PII. The data-prep "
                    "audit's own scan is heuristic regex and not compliance-grade; this is.",
        s3JobDefinition={
            "bucketDefinitions": [{"accountId": account_id, "buckets": [bucket]}],
            # Scoped to the prefix the console's presigned upload writes to. Without this the
            # job would also read runs/ and finops/ -- our own artifacts, paid for by the GB,
            # and none of them customer data.
            "scoping": {"includes": {"and": [{"simpleScopeTerm": {
                "comparator": "STARTS_WITH", "key": "OBJECT_KEY",
                "values": [f"{CUSTOMER_DATA_PREFIX}/"]}}]}},
        },
        # RECOMMENDED, not ALL: ALL turns on all 166 managed identifiers including ones for
        # regions and document types this pipeline never sees, and every extra identifier is
        # a false positive an operator has to triage before the real ones are visible.
        managedDataIdentifierSelector="RECOMMENDED",
        tags={TAG_KEY: TAG_VAL})
    res["job_id"] = job.get("jobId")
    res["coverage"] = f"created SCHEDULED daily job over {CUSTOMER_DATA_PREFIX}/"
    return res


def ensure_bus(events, dry):
    try:
        events.describe_event_bus(Name=EVENT_BUS)
        return "exists"
    except Exception:
        pass
    if dry:
        return "would create"
    events.create_event_bus(Name=EVENT_BUS,
                            Tags=[{"Key": TAG_KEY, "Value": TAG_VAL}])
    return "created"


def ensure_topic(sns, topic_arn, dry, email=None):
    """Create the escalation topic and make sure SOMEONE is listening.

    The topic existed from Phase 3 with zero subscribers, so every escalation the
    pipeline raised -- an agent stopping to ask a human about a budget overrun, a
    quality gate failing, a remediation budget exhausted -- published successfully
    into nothing. An escalation nobody receives is worse than none at all: the run
    waits and the design claims a human was asked.

    The deploy cannot invent an address, so: subscribe one when given (idempotent --
    SNS ignores a repeat of the same endpoint), and when nobody at all is subscribed,
    say so in the output rather than reporting the topic as healthy.
    """
    status = "exists"
    arn = topic_arn
    try:
        sns.get_topic_attributes(TopicArn=topic_arn)
    except Exception:
        if dry:
            return {"status": "would create", "arn": topic_arn}
        # create_topic is itself idempotent by name
        arn = sns.create_topic(Name=SNS_TOPIC,
                               Tags=[{"Key": TAG_KEY, "Value": TAG_VAL}])["TopicArn"]
        status = "created"

    if dry:
        return {"status": status, "arn": arn,
                "subscribers": f"would subscribe {email}" if email else "unchanged"}

    subs = sns.list_subscriptions_by_topic(TopicArn=arn).get("Subscriptions", [])
    existing = {s.get("Endpoint") for s in subs}
    if email and email not in existing:
        sns.subscribe(TopicArn=arn, Protocol="email", Endpoint=email,
                      ReturnSubscriptionArn=True)
        subs.append({"Endpoint": email, "SubscriptionArn": "pending confirmation"})

    note = f"{len(subs)} subscriber(s)"
    if not subs:
        note = ("NO SUBSCRIBERS -- every escalate_human call publishes into the void. "
                "Re-run with --escalation-email <addr> so a human actually hears them.")
    # A subscription stays PendingConfirmation until the recipient clicks the link;
    # reporting it as subscribed would be the same silence in a new place.
    pending = [s["Endpoint"] for s in subs
               if str(s.get("SubscriptionArn", "")).lower().find("pending") >= 0]
    if pending:
        note += f" (awaiting email confirmation: {', '.join(pending)})"
    return {"status": status, "arn": arn, "subscribers": note}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--region", required=True)
    ap.add_argument("--account-id", help="skip STS (offline dry-run) and use this account id")
    ap.add_argument("--bucket", help="bucket name (default llmops-agentic-<acct>-<region>)")
    ap.add_argument("--console-origin",
                    help="browser origin allowed to PUT customer datasets, e.g. "
                         "https://abc123.execute-api.us-east-1.amazonaws.com. Auto-"
                         f"resolved from the {CONSOLE_FN}-api HTTP API when omitted; CORS "
                         "is SKIPPED (never wildcarded) if it cannot be resolved.")
    ap.add_argument("--skills-src",
                    help="checkout of the MLOps-agent-skills repo to mirror into "
                         f"s3://<bucket>/skills/. Every SKILL.md is validated for YAML "
                         "frontmatter BEFORE upload, because a bad skill source is "
                         "accepted by UpdateHarness and then fails at session start. "
                         "Omitted: the step is skipped and says so.")
    ap.add_argument("--enable-pii-scan", action="store_true",
                    help=f"create a SCHEDULED Macie classification job over "
                         f"{CUSTOMER_DATA_PREFIX}/ (billed per GB scanned, and it re-scans "
                         "daily on its own). Omitted: nothing is created, but the coverage "
                         "gap is still REPORTED -- the account's Macie session being "
                         "ENABLED is not coverage.")
    ap.add_argument("--escalation-email",
                    help="subscribe this address to llmops-escalations (idempotent). "
                         "Without a subscriber, escalate_human publishes into the void.")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    account_id = args.account_id
    if not account_id:
        account_id = boto3.client("sts", region_name=args.region).get_caller_identity()["Account"]
    bucket = args.bucket or f"llmops-agentic-{account_id}-{args.region}"
    topic_arn = f"arn:aws:sns:{args.region}:{account_id}:{SNS_TOPIC}"

    s3 = safe_client("s3", args.region, args.dry_run)
    ddb = safe_client("dynamodb", args.region, args.dry_run)
    events = safe_client("events", args.region, args.dry_run)
    sns = safe_client("sns", args.region, args.dry_run)

    results = {}
    origin = console_origin(args.region, args.dry_run, args.console_origin)
    results["bucket"] = {
        "name": bucket,
        "status": ensure_bucket(s3, bucket, args.region, args.dry_run),
        "settings": "versioning=on sse=AES256 public-access-block=ALL "
                    f"lifecycle=runs/ expire {RUNS_EXPIRE_DAYS}d",
        # Reported as its own line, not folded into `settings`: when CORS is skipped the
        # symptom is a browser upload that fails with no server-side trace, so the deploy
        # output is the only place anyone will see it.
        "cors": ensure_cors(s3, bucket, origin, args.dry_run),
    }
    # Its own line for the same reason as CORS and skills: when nothing scans the customer's
    # data the only other symptom is a readiness panel that reads as if someone had.
    results["pii_scan"] = ensure_pii_scan(
        safe_client("macie2", args.region, args.dry_run), bucket, account_id,
        args.dry_run, args.enable_pii_scan)
    results["contracts"] = ensure_contracts(s3, bucket, args.dry_run)
    # Reported on its own line for the same reason as CORS: when this is skipped there is
    # no other visible symptom until a source is switched and every session fails at start.
    results["skills"] = ensure_skills(s3, bucket, args.dry_run, args.skills_src)
    results["code"] = ensure_code(s3, bucket, args.dry_run)
    results["eval_instrument"] = ensure_eval_instrument(s3, bucket, args.dry_run)
    results["vision_code"] = ensure_vision_code(s3, bucket, args.dry_run)
    results[RUNS_TABLE] = {
        "status": ensure_table(ddb, RUNS_TABLE, {
            "AttributeDefinitions": [
                {"AttributeName": "run_id", "AttributeType": "S"},
                {"AttributeName": "job_name", "AttributeType": "S"},
            ],
            "KeySchema": [{"AttributeName": "run_id", "KeyType": "HASH"}],
            "GlobalSecondaryIndexes": [{
                "IndexName": "job_name-index",
                "KeySchema": [{"AttributeName": "job_name", "KeyType": "HASH"}],
                "Projection": {"ProjectionType": "ALL"},
            }],
        }, args.dry_run, pitr=True),
        "schema": "PK run_id (S), GSI job_name-index, on-demand, PITR on",
    }
    results[EVENTS_TABLE] = {
        "status": ensure_table(ddb, EVENTS_TABLE, {
            "AttributeDefinitions": [
                {"AttributeName": "run_id", "AttributeType": "S"},
                {"AttributeName": "sk", "AttributeType": "S"},
            ],
            "KeySchema": [
                {"AttributeName": "run_id", "KeyType": "HASH"},
                {"AttributeName": "sk", "KeyType": "RANGE"},
            ],
        }, args.dry_run),
        "schema": "PK run_id (S), SK sk (S), on-demand",
    }
    results[ESTIMATES_TABLE] = {
        "status": ensure_table(ddb, ESTIMATES_TABLE, {
            "AttributeDefinitions": [
                {"AttributeName": "id", "AttributeType": "S"},
                {"AttributeName": "project", "AttributeType": "S"},
                {"AttributeName": "created_at", "AttributeType": "S"},
            ],
            "KeySchema": [{"AttributeName": "id", "KeyType": "HASH"}],
            # The approval queue and the project rollup both read "this project's
            # estimates, newest first". Without this GSI both would be table scans,
            # and the queue is on the dashboard's default render path.
            "GlobalSecondaryIndexes": [{
                "IndexName": "project-created_at-index",
                "KeySchema": [
                    {"AttributeName": "project", "KeyType": "HASH"},
                    {"AttributeName": "created_at", "KeyType": "RANGE"},
                ],
                "Projection": {"ProjectionType": "ALL"},
            }],
        }, args.dry_run, pitr=True),
        "schema": "PK id (S), GSI project-created_at-index, on-demand, PITR on "
                  "(approval decisions are audit records)",
    }
    results[ACTUALS_TABLE] = {
        "status": ensure_table(ddb, ACTUALS_TABLE, {
            "AttributeDefinitions": [
                {"AttributeName": "project", "AttributeType": "S"},
                {"AttributeName": "sk", "AttributeType": "S"},
            ],
            "KeySchema": [
                {"AttributeName": "project", "KeyType": "HASH"},
                {"AttributeName": "sk", "KeyType": "RANGE"},
            ],
        }, args.dry_run, pitr=True),
        "schema": "PK project (S), SK sk = <period>#<run_id|audit|finding>#<...>, "
                  "on-demand, PITR on",
    }
    results[TASKS_TABLE] = {
        "status": ensure_table(ddb, TASKS_TABLE, {
            "AttributeDefinitions": [
                {"AttributeName": "id", "AttributeType": "S"},
            ],
            "KeySchema": [{"AttributeName": "id", "KeyType": "HASH"}],
        }, args.dry_run, pitr=True),
        "schema": "PK id (S, task- prefix), on-demand, PITR on; list via scan "
                  "(deliberate simplification — consultation volumes are tiny)",
    }
    results["event_bus"] = {"name": EVENT_BUS, "status": ensure_bus(events, args.dry_run)}
    topic = ensure_topic(sns, topic_arn, args.dry_run, args.escalation_email)
    topic_arn = topic["arn"]
    results["sns_topic"] = {"name": SNS_TOPIC, "status": topic["status"],
                            "subscribers": topic.get("subscribers", "")}
    kms_client = safe_client("kms", args.region, args.dry_run)
    key_status, key_arn = ensure_approval_key(kms_client, account_id, args.dry_run)
    results["approval_key"] = {"alias": APPROVAL_KEY_ALIAS, "status": key_status,
                               "arn": key_arn}

    params = {
        "bucket": bucket,
        "runs_table": RUNS_TABLE,
        "events_table": EVENTS_TABLE,
        "estimates_table": ESTIMATES_TABLE,
        "actuals_table": ACTUALS_TABLE,
        "tasks_table": TASKS_TABLE,
        "event_bus": EVENT_BUS,
        "escalations_topic_arn": topic_arn,
    }
    if key_arn:
        params["approval_key_arn"] = key_arn
    if not args.dry_run:
        ssm = boto3.client("ssm", region_name=args.region)
        for k, v in params.items():
            ssm.put_parameter(Name=f"/llmops/storage/{k}", Value=v,
                              Type="String", Overwrite=True)
    results["ssm_params"] = [f"/llmops/storage/{k}" for k in params]
    results["dry_run"] = args.dry_run

    print(json.dumps(results, indent=2))
    return 0


if __name__ == "__main__":
    sys.exit(main())
